### PR TITLE
fix(detail page): Align center

### PR DESCRIPTION
**Pull request by pacokwon**
Align Masonry to center. Apply responsive layout.

#17

### CODE REVIEW

**Review by jungdj — CHANGES_REQUESTED** [review]
Fix following the code format

**Review by jungdj — CHANGES_REQUESTED** [review]
Resolve merge conflict

**Comment by pacokwon** [comment]
Code changes already applied in feature/prettier branch's pull request....
Gaemang...

**Comment by pacokwon** [comment]
<h1>I'm sorry</h1>

**Pull request closed without merging**
